"""Initial migrate

Revision ID: 1335ef379098
Revises: 
Create Date: 2024-09-19 19:55:05.664913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1335ef379098"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_class_name"), "class", ["name"], unique=False)
    op.create_table(
        "classroom",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classroom_name"), "classroom", ["name"], unique=False)
    op.create_table(
        "classroom_user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("first_name", sa.String(length=320), nullable=False),
        sa.Column("second_name", sa.String(length=320), nullable=False),
        sa.Column("third_name", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_teacher", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classroom_user_email"), "classroom_user", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_classroom_user_first_name"),
        "classroom_user",
        ["first_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classroom_user_second_name"),
        "classroom_user",
        ["second_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classroom_user_third_name"),
        "classroom_user",
        ["third_name"],
        unique=False,
    )
    op.create_table(
        "class_classroom",
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("classroom_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classroom.id"],
        ),
    )
    op.create_table(
        "class_users",
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["classroom_user.id"],
        ),
    )
    op.create_table(
        "material",
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("classroom", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column(
            "material_type",
            sa.Enum("HOMEWORK", "MESSAGE", "MATERIALS", name="classmaterialstype"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom"],
            ["classroom.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["classroom_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_material_classroom"), "material", ["classroom"], unique=False
    )
    op.create_table(
        "commentary_material",
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("material", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["material"],
            ["material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_material",
        sa.Column("file", sa.LargeBinary(), nullable=False),
        sa.Column("material", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["material"],
            ["material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "homework",
        sa.Column("evaluation", sa.Integer(), nullable=True),
        sa.Column("material", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["material"],
            ["material.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["classroom_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_homework",
        sa.Column("file", sa.LargeBinary(), nullable=False),
        sa.Column("homework", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["homework"],
            ["homework.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_homework")
    op.drop_table("homework")
    op.drop_table("file_material")
    op.drop_table("commentary_material")
    op.drop_index(op.f("ix_material_classroom"), table_name="material")
    op.drop_table("material")
    op.drop_table("class_users")
    op.drop_table("class_classroom")
    op.drop_index(op.f("ix_classroom_user_third_name"), table_name="classroom_user")
    op.drop_index(op.f("ix_classroom_user_second_name"), table_name="classroom_user")
    op.drop_index(op.f("ix_classroom_user_first_name"), table_name="classroom_user")
    op.drop_index(op.f("ix_classroom_user_email"), table_name="classroom_user")
    op.drop_table("classroom_user")
    op.drop_index(op.f("ix_classroom_name"), table_name="classroom")
    op.drop_table("classroom")
    op.drop_index(op.f("ix_class_name"), table_name="class")
    op.drop_table("class")
    # ### end Alembic commands ###
